version: "3.9"

services:
  db:
    image: postgres:16
    container_name: backend_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forum_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/database/migration:/docker-entrypoint-initdb.d

  backend:
    build: .
    image: backend_docker
    container_name: backend_app
    depends_on:
      - db
    environment:
      PORT: ":5000"
      DATABASE_URL: postgresql://postgres:postgres@db:5432/forum_db?sslmode=disable
    ports:
      - "5000:5000"
    restart: always
